name: ArduinoCI
on: [push]
jobs:
  test:
    name: "test: ${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        board:
          - vendor: teensy
            arch: avr
            name: teensy41
        include:
          - index: https://www.pjrc.com/teensy/package_teensy_index.json
            board:
              vendor: teensy
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: install arduino and run test
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
            - source-url: ${{matrix.index}}
          sketch-paths: "./"
